version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run: 
          name: split tests
          command: |
            circleci tests glob "src/*.sh" | circleci tests split > /tmp/tests-to-run
      - run:
          name: Run /tmp/tests-to-run
          command: |
            chmod +x /tmp/tests-to-run
            bash /tmp/tests-to-run

workflows:
  test:
    jobs:
      - test